update snark input
0xPolygonHermez/zkevm-contracts pull request #51
Opened 2022-08-05 13:29 UTC by invocamanman

- Update snark Input

2022-08-05 14:07 UTC, krlosMata requested changes

2022-08-05 14:07 UTC, krlosMata commented on contracts/ProofOfEfficiency.sol
> +            // Set the actua length of the input bytes
```suggestion
            // Set the actual length of the input bytes
```

2022-08-05 14:07 UTC, krlosMata commented on contracts/ProofOfEfficiency.sol
> +import "hardhat/console.sol";
I guess it was for debugging xD

2022-08-05 14:07 UTC, krlosMata commented on contracts/ProofOfEfficiency.sol
> +            // Set the pointer at the begining of the byte array
```suggestion
            // Set the pointer at the beginning of the byte array
```

2022-08-05 14:07 UTC, krlosMata commented on test/contracts/proofOfEfficiency.test.js
>          const inputSnarkSC = await proofOfEfficiencyContract.calculateSnarkInput(
Add unitary test checking values compared with JS version in https://github.com/0xPolygonHermez/zkevm-commonjs/blob/main/test/contract-utils.test.js#L16

2022-08-05 15:14 UTC, krlosMata approved these changes
:smile_cat:

2022-08-08 08:05 UTC, ignasirv approved these changes
💯

2022-08-08 08:16 UTC, merged