Feature/add upgradability
0xPolygonHermez/zkevm-contracts pull request #52
Opened 2022-08-29 11:00 UTC by invocamanman

- Add upgradabiltiy
- Update deployments
- Add permit function

2022-08-30 15:07 UTC, ignasirv commented on contracts/Bridge.sol
> +            "HezMaticMerge::_permit: NOT_VALID_CALL"
Change HezMaticMerge to Bridge

2022-09-02 07:56 UTC, krlosMata requested changes

2022-09-02 07:56 UTC, krlosMata commented on test/contracts/helpers/permit-helper.js
> +async function createPermitSignature(tokenContractInstance, wallet, spenderAddress, value, nonce, deadline) {
Add comments

2022-09-02 07:56 UTC, krlosMata commented on test/contracts/helpers/permit-helper.js
> +const ifacePermit = new ethers.utils.Interface(['function permit(address,address,uint256,uint256,uint8,bytes32,bytes32)']);
Add comments

2022-09-02 07:56 UTC, krlosMata commented on package.json
>  {
If `permit-helper.js` is meant to be used by third-parties I would include it in the `index.js`

2022-09-02 07:56 UTC, krlosMata commented on docker/Dockerfile.geth
> +FROM ethereum/client-go
We decided to hardcode a version for `ethereum/client-go` in order to have always the same deployment and to not be dependent on changes in `ethereum/client-go` versions. This has been a source of issues in the past.
Therefore, I would setup a concrete version (to decode with `zkNode` team).
If needed, the version will be updated.

2022-09-02 13:43 UTC, krlosMata approved these changes
:smile_cat:

2022-09-02 13:52 UTC, laisolizq approved these changes
:smile_cat:

2022-09-02 13:53 UTC, merged