Feature/update upgrade script
0xPolygonHermez/zkevm-contracts pull request #79
Opened 2023-01-03 15:16 UTC by invocamanman

- Upgrade script hackmd updated

2023-01-03 15:52 UTC, ignasirv approved these changes
💯

2023-01-03 16:29 UTC, krlosMata requested changes

2023-01-03 16:29 UTC, krlosMata commented on deployment/README.md
> +- `gensis.json` has been generated using the tool: `src/create-genesis.js` using as generator file: `genesis-gen.json`
```suggestion
- `genesis.json` has been generated using the tool: `src/create-genesis.js` using as generator file: `genesis-gen.json`
```

2023-01-03 16:29 UTC, krlosMata commented on upgrade/README.md
> +Otherwise, inc ase of timelock use `timeLockUpgrade.js`
```suggestion
Otherwise, in case of timelock use `timeLockUpgrade.js`
```

2023-01-03 16:29 UTC, krlosMata commented on upgrade/README.md
> +- With the owner of the timelock ( multisig or account), send the data printed by `schedule` to the `Timelock` contract.
```suggestion
- With the owner of the timelock (multisig or account), send the data printed by `schedule` to the `Timelock` contract.
```

2023-01-03 16:29 UTC, krlosMata commented on upgrade/README.md
> +- Once the necessary timeout has pass, with the same account you can now send the data printed by `execute` to the `Timelock` contract and the contracts will be upgraded.
```suggestion
- Once the necessary timeout has expired, with the same account you can now send the data printed by `execute` to the `Timelock` contract and the contracts will be upgraded.
```

2023-01-03 16:29 UTC, krlosMata commented on upgrade/simpleUpgradeScript.js
> +    const proxyPolygonAddress = '0xfefefefefefefefefefefefee';
This parameter should be loaded by `cli` or `input-upgrade.json`

2023-01-03 16:29 UTC, krlosMata commented on upgrade/timeLockUpgrade.js
>      // compìle contracts
Output with upgrade information should be provided as well in json format

2023-01-09 08:18 UTC, krlosMata requested changes

2023-01-09 08:18 UTC, krlosMata commented on upgrade/timeLockUpgrade.js
> +        // Executre operation
```suggestion
        // Execute operation
```

2023-01-09 08:18 UTC, krlosMata commented on upgrade/timeLockUpgrade.js
> +    for (const upgrade of upgradeParameters.upgrades) {
I would check in advance `upgrade.contractName` existence

2023-01-09 14:47 UTC, krlosMata approved these changes
:smile_cat:

2023-01-09 14:47 UTC, merged